// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    MonCard: typeof import('./components/MonCard.vue')['default']
    MonFooter: typeof import('./components/MonFooter.vue')['default']
    PokeHeader: typeof import('./components/PokeHeader.vue')['default']
    PokeMainHeader: typeof import('./components/PokeMainHeader.vue')['default']
    README: typeof import('./components/README.md')['default']
    TrainerImg: typeof import('./components/TrainerImg.vue')['default']
  }
}

export { }
